##Importing the libraries and dataset

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [ ]:
dataset = pd.read_csv('NLP.tsv', delimiter='\t' , quoting=3)

##Cleaning the dataset

In [ ]:
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
corpus = []
for i in range(0 , 10600):
  review = re.sub('[^a-zA-Z]' , ' ' , dataset['summary'][i])
  review = review.lower()
  review = review.split()
  ps = PorterStemmer()
  all_stopwords = stopwords.words('english')
  all_stopwords.remove('not')
  review = [ps.stem(word) for word in review if not word in set(all_stopwords)]
  review = ' '.join(review)
  corpus.append(review)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [ ]:
print(corpus)

['great nutmeg', 'handl problem', 'great zester made rest obsolet', 'hope', 'fabul zester', 'utilitarian essenti', 'best grate laundri soap make home made deterg', 'zest well clean easi', 'cook love tool except', 'awesom grater', 'perfect', 'sheath', 'zester cover', 'best', 'mom say none flavor get lost', 'wonder', '', 'amaz', 'microplan classic zester grater sharp', 'great small grater', 'use grate carrot soup', 'perfect parmesan perform', 'kitchen essenti', 'love durabl effect', 'best grater ever', 'bought husband think winner', 'make zest snap', 'wow', 'great product', 'everi kitchen need one', 'great', 'grater', 'good zester food get stuck', 'cant without', 'almost perfect', 'love thing', '', 'work great', 'microplan grater', 'great tool', 'work well', 'love', 'zester', 'job', 'microplan grater zester handiest gadget ever', 'overr', 'nice fine zest', 'great product', 'beat classic', 'high qualiti made usa', 'love', 'great product', 'kitchen essenti', 'great zester', 'gadget lover l

##Creating Bag of Words model 

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 1500)
x = cv.fit_transform(corpus).toarray()
y = dataset.iloc[: , -1].values

##Spliting the dataset into Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.25 , random_state = 0)

##Training the model

In [ ]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(x_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

##Predict the results

In [ ]:
y_pred = classifier.predict(x_test)
pred = np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1)

In [ ]:
pred

array([[1, 1],
       [1, 0],
       [1, 1],
       ...,
       [1, 1],
       [1, 1],
       [0, 1]])

In [ ]:
test = pd.read_csv('test.tsv', delimiter='\t' ,quoting=3)
pred = []
for i in range(0 , 10600):
  new_review = test['summary'][i]
  new_review = re.sub('[^a-zA-Z]', ' ', new_review)
  new_review = new_review.lower()
  new_review = new_review.split()
  ps = PorterStemmer()
  all_stopwords = stopwords.words('english')
  all_stopwords.remove('not')
  new_review = [ps.stem(word) for word in new_review if not word in set(all_stopwords)]
  new_review = ' '.join(new_review)
  new_corpus = [new_review]
  new_X_test = cv.transform(new_corpus).toarray()
  new_y_pred = classifier.predict(new_X_test)
  pred.append(new_y_pred)

In [ ]:
pred1 = np.array(pred)
pred1

array([[1],
       [1],
       [1],
       ...,
       [1],
       [1],
       [1]])

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test , y_pred)
print(cm)
print(accuracy_score(y_test , y_pred))

[[ 174  282]
 [  54 2140]]
0.8732075471698113


In [ ]:
ds1 = pd.read_csv('mainsalesdata.csv')
x1 = ds1.iloc[: , :].values

In [ ]:
dataset1 = pd.DataFrame({'Date':x1[: , 0],'Store':x1[: , 1],'DayOfWeek':x1[: , 2],'WeekofMonth':x1[: , 3],'Month':x1[: , 4],'Customers':x1[: , 5],'Open':x1[: , 6],'Promo':x1[: , 7],'StateHoliday':x1[: , 8],'StateHoliday':x1[: , 9],'StoreType':x1[: , 10],'Assortment':x1[: , 11],'CompetitionDistance':x1[: , 12],'Rating':x1[: , 13],'Reviews':pred1[: , 0],'Sales':x1[: , 14]})

In [ ]:
dataset1

Date Store DayOfWeek  ... Rating Reviews  Sales
0       1/1/2020     1         4  ...      0       1      0
1       1/1/2020     2         4  ...      0       1      0
2       1/1/2020     3         4  ...      0       1      0
3       1/1/2020     4         4  ...      0       1      0
4       1/1/2020     5         4  ...      0       1      0
...          ...   ...       ...  ...    ...     ...    ...
10595  7/31/2020    46         5  ...      3       0   7628
10596  7/31/2020    47         5  ...      4       1   9379
10597  7/31/2020    48         5  ...      2       1   3874
10598  7/31/2020    49         5  ...      4       1  10310
10599  7/31/2020    50         5  ...      3       1   5729

[10600 rows x 15 columns]

In [ ]:
dataset1.to_csv("Output12.csv",index=False)

In [ ]:
dataset = pd.read_csv('Output12.csv')
x = dataset.iloc[: , 5:-1].values
y = dataset.iloc[: , -1].values

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[: , 4] = le.fit_transform(x[: , 4])

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[: , 5] = le.fit_transform(x[: , 5])

In [ ]:
x = np.asarray(x).astype('float32')

In [ ]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x , y , random_state = 0 , test_size = 0.25)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train= sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [ ]:
ann = tf.keras.models.Sequential()

In [ ]:
ann.add(tf.keras.layers.Dense(units=10, activation='relu'))

In [ ]:
ann.add(tf.keras.layers.Dense(units=10, activation='relu'))

In [ ]:
ann.add(tf.keras.layers.Dense(units=1 , activation='relu'))

In [ ]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

In [ ]:
ann.fit(x_train , y_train , epochs= 1500 , batch_size= 32)

Epoch 1/1500
249/249 [==============================] - 0s 1ms/step - loss: 42921584.0000
Epoch 2/1500
249/249 [==============================] - 0s 1ms/step - loss: 41903004.0000
Epoch 3/1500
249/249 [==============================] - 0s 989us/step - loss: 38334808.0000
Epoch 4/1500
249/249 [==============================] - 0s 983us/step - loss: 31653966.0000
Epoch 5/1500
249/249 [==============================] - 0s 1ms/step - loss: 22859788.0000
Epoch 6/1500
249/249 [==============================] - 0s 1ms/step - loss: 14243682.0000
Epoch 7/1500
249/249 [==============================] - 0s 1ms/step - loss: 7969298.5000
Epoch 8/1500
249/249 [==============================] - 0s 977us/step - loss: 4636994.5000
Epoch 9/1500
249/249 [==============================] - 0s 1ms/step - loss: 3257305.2500
Epoch 10/1500
249/249 [==============================] - 0s 1ms/step - loss: 2656623.5000
Epoch 11/1500
249/249 [==============================] - 0s 1ms/step - loss: 2300452.5000
Epoch 1

In [ ]:
y_pred = ann.predict(x_test)
np.set_printoptions(precision=2)
Pred = np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1)

In [ ]:
dataset2 = pd.DataFrame({'Predicted Values': Pred[:, 0], 'True Values': Pred[:, 1]})

In [ ]:
print(dataset2)

      Predicted Values  True Values
0             0.000000          0.0
1          5000.652344       5992.0
2         11356.500000      12763.0
3          8900.088867      10284.0
4          8164.369629       9504.0
...                ...          ...
2645       4680.640625       4865.0
2646       6202.189453       7301.0
2647       2823.334229       3005.0
2648          0.000000          0.0
2649       6045.303711       6346.0

[2650 rows x 2 columns]


In [ ]:
dataset2.to_csv("predvalues.csv",index=False)

In [ ]:
y_error = list()
PE = 0
for i in range(len(y_pred)):
  if y_test[i] == 0:
    i += 1
  else:
    AE = abs(y_test[i] - y_pred[i])
    PE += (AE / y_test[i]) * 100
    y_error = PE / len(y_pred)

In [ ]:
acc = list()
for i in range(len(y_pred)):
  if y_test[i] == 0:
    i += 1
    acc.append(0)
  else:
    AE = abs(y_test[i] - y_pred[i])
    PE = int((AE / y_test[i]) * 100)
    acc.append(PE)

In [ ]:
dataset2 = pd.DataFrame({'Predicted Values': Pred[:, 0], 'True Values': Pred[:, 1], 'Error percentage':acc})

In [ ]:
dataset2

Predicted Values  True Values  Error percentage
0             0.000000          0.0                 0
1          5000.652344       5992.0                16
2         11356.500000      12763.0                11
3          8900.088867      10284.0                13
4          8164.369629       9504.0                14
...                ...          ...               ...
2645       4680.640625       4865.0                 3
2646       6202.189453       7301.0                15
2647       2823.334229       3005.0                 6
2648          0.000000          0.0                 0
2649       6045.303711       6346.0                 4

[2650 rows x 3 columns]

In [ ]:
dataset2.to_csv("predvalues1.csv",index=False)

In [ ]:
print(y_error)

[6.52]
